name: Sync Watering Records

on:
  issues:
    types: [opened]

jobs:
  sync-records:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.FLOWER_WATERING_TOKEN }}  # 引用Secrets中的Token
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.FLOWER_WATERING_TOKEN }}  # 推送变更所需的权限

    - name: Parse issue data
      id: parse-issue
      uses: actions/github-script@v5
      with:
        script: |
          const issue = context.payload.issue
          // 解析逻辑保持不变...
          return { type, date, user, timestamp, id }

    - name: Update records.json
      if: steps.parse-issue.outputs.result != ''
      run: |
        # 下载当前records.json
        curl -s -o data/records.json \
          "https://raw.githubusercontent.com/${{ github.repository }}/main/data/records.json?t=$(date +%s)"
        
        # 添加新记录（需提前安装jq）
        echo '${{ steps.parse-issue.outputs.result }}' > new-record.json
        jq --argfile new new-record.json '. += [$new]' data/records.json > updated.json
        
        # 提交更改
        mv updated.json data/records.json
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/records.json
        git commit -m "Add record from issue #${{ github.event.issue.number }}"
        git push
